services:
  glances:
    image: nicolargo/glances@sha256:af1b6ccd3c33f7ac821e30b7dd58946542ce3e252b225dc3d678a1ca48f1007b
    container_name: glances-lenovo
    restart: unless-stopped
    pid: host
    ports:
    - ${LENOVO_IP:?Set LENOVO_IP}:61208:61208
    environment:
      TZ: Europe/Athens
      GLANCES_OPT: -w
    volumes:
    - /:/rootfs:ro
    - /etc/os-release:/etc/os-release:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    mem_limit: 256m
    cpus: 0.35
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
