services:
  explo:
    image: ghcr.io/lumepart/explo@sha256:680eac0592d013aac8768e2c3bae02345f74083f3a4585337420446764eb66fc
    container_name: explo
    restart: always
    ports:
    - ${HOMELAB_IP:?Set HOMELAB_IP}:7288:7288
    extra_hosts:
    - host.docker.internal:host-gateway
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/Athens
      WEB_UI: 'true'
      EXECUTE_ON_START: 'false'
    volumes:
    - ./.env:/opt/explo/.env
    - ./config:/opt/explo/config
    - ${MEDIA_ROOT:-/srv/media}/Music/Explo:/data
    - ${MEDIA_ROOT:-/srv/media}/Downloads/slskd/complete:/slskd
    mem_limit: 768m
    cpus: 1.0
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
