services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr@sha256:f9151e5bc1025c6d0a630d503210cdcb6bb55a7cc098562609d96a408d838902
    container_name: prowlarr
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Athens
    volumes:
    - ./config:/config
    ports:
    - 9696:9696
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.75
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
