services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - ./config:/config
      - ${MEDIA_ROOT:-/srv/media}:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
    mem_limit: 768m
    cpus: 1.00
